services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ideaboard_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: production
      PORT: 3001
      HOST: 0.0.0.0
      # DATABASE_URL is loaded from env_file above
      JWT_SECRET: your-super-secure-jwt-secret-key-change-in-production
      CORS_ORIGIN: http://localhost:3000
      RATE_LIMIT_MAX: 100
      RATE_LIMIT_WINDOW: 60000
      LOG_LEVEL: info
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://0.0.0.0:3001/api/health >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ideaboard_network

  # Frontend Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ideaboard_frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:3001/api
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://0.0.0.0:3000 >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ideaboard_network

networks:
  ideaboard_network:
    driver: bridge